-- VERITABANINI OLUSTURYORUZ
CREATE SCHEMA `my_company_db` DEFAULT CHARACTER SET utf32 COLLATE utf32_bin ;





--  MUSTERILER TABLOSU
CREATE TABLE `my_company_db`.`customers` (
                                             `ID` INT NOT NULL AUTO_INCREMENT,
                                             `FIRST_NAME` VARCHAR(60) NULL,
                                             `LAST_NAME` VARCHAR(60) NULL,
                                             PRIMARY KEY (`ID`));





-- URUNLER TABLOSU
CREATE TABLE `my_company_db`.`products` (
                                            `ID` INT NOT NULL AUTO_INCREMENT,
                                            `PROD_NAME` VARCHAR(200) NULL,
                                            `PROD_CODE` VARCHAR(45) NULL,
                                            PRIMARY KEY (`ID`));

-- TABLO UZERINDE DEGISIKLIK YAPAR
ALTER TABLE `my_company_db`.`products`
    CHANGE COLUMN `PROD_Code` `PROD_CODE` VARCHAR(45) NULL DEFAULT NULL ;

-- URUNLER TABLOLSUNU SILER
-- DROP TABLE `mycompany`.`products`;

-- VERITABINI SILER
-- DROP DATABASE `my_company_db`;



-- MUSTERI TABLOSUNA KAYITLAR EKLENDI
INSERT INTO `my_company_db`.`customers` (`FIRST_NAME`, `LAST_NAME`) VALUES ('Mahmut', 'Sakarya');
INSERT INTO `my_company_db`.`customers` (`FIRST_NAME`, `LAST_NAME`) VALUES ('Hakan', 'Metin');
INSERT INTO `my_company_db`.`customers` (`FIRST_NAME`, `LAST_NAME`) VALUES ('Mücahit', 'Özcan');

-- MUSTERILERI LISTELE GOSTER
SELECT * FROM `my_company_db`.`customers`;



-- SADECE 1 KAYIT EKLE
INSERT INTO `my_company_db`.`customers`
(`FIRST_NAME`, `LAST_NAME`)
VALUES ('Tuana', 'Kaymaz');

-- SADECE 1 KAYIT EKLE
INSERT INTO my_company_db.customers
(FIRST_NAME, LAST_NAME)
VALUES('Sefa', 'Küçükarslan');

-- MUSTERILERI LISTELE GOSTER
SELECT * FROM my_company_db.customers;



-- TABLOYA 2 TANE YENI KOLON EKLEDIK VE 3 KOLON UZERINDE DE DEGISIKLIK YAPTIK
ALTER TABLE `my_company_db`.`customers`
    ADD COLUMN `AGE` SMALLINT(3) NULL AFTER `LAST_NAME`,
    ADD COLUMN `COUNTRY` VARCHAR(65) NULL AFTER `AGE`,
    CHANGE COLUMN `ID` `CUSTOMER_ID` INT NOT NULL ,
    CHANGE COLUMN `FIRST_NAME` `FIRST_NAME` VARCHAR(70) NULL DEFAULT NULL ,
    CHANGE COLUMN `LAST_NAME` `LAST_NAME` VARCHAR(75) NULL DEFAULT NULL ;


-- TABLODA YENI EKLENEN KOLONLARA DEGER GIRILDI
UPDATE `my_company_db`.`customers` SET `AGE` = '30', `COUNTRY` = 'TR' WHERE (`CUSTOMER_ID` = '1');
UPDATE `my_company_db`.`customers` SET `AGE` = '22', `COUNTRY` = 'BR' WHERE (`CUSTOMER_ID` = '2');
UPDATE `my_company_db`.`customers` SET `AGE` = '25', `COUNTRY` = 'DE' WHERE (`CUSTOMER_ID` = '3');
UPDATE `my_company_db`.`customers` SET `AGE` = '27', `COUNTRY` = 'GB' WHERE (`CUSTOMER_ID` = '4');
UPDATE `my_company_db`.`customers` SET `AGE` = '32', `COUNTRY` = 'TR' WHERE (`CUSTOMER_ID` = '5');


-- MUSTERILERI LISTELE GOSTER
SELECT * FROM `my_company_db`.`customers`;



-- SADECE 2 KOLON SECILDI - MUSTERILERI LISTELE GOSTER
SELECT customers.FIRST_NAME, customers.LAST_NAME  FROM `my_company_db`.`customers`;



-- SADECE 3 KOLON SECILDI - MUSTERILERI LISTELE GOSTER
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME  FROM `my_company_db`.`customers`;


-- ULKESI TR OLAN MUSTERILERI GETIR
SELECT * FROM my_company_db.customers
WHERE COUNTRY = 'TR';

-- VE KULLANIMI - ULKESI TR ve SOYADI 'Sakarya' OLAN MUSTERILERI GETIR
SELECT * FROM my_company_db.customers
WHERE COUNTRY = 'TR' AND  customers.LAST_NAME = 'Sakarya';


-- VEYA KULLANIMI - ULKESI TR veya SOYADI 'Metin' OLAN MUSTERILERI GETIR
SELECT *
FROM customers
WHERE COUNTRY = 'TR'  OR  LAST_NAME = 'Metin';


-- ISIM VE SOYISIM KOLONLARINI SEC - ULKESI TR veya SOYADI 'Metin' OLAN MUSTERILERI GETIR
SELECT FIRST_NAME, LAST_NAME
FROM customers
WHERE COUNTRY = 'TR'  OR  LAST_NAME = 'Metin';


-- YASI 27'DEN BUYUK OLANLARI GETIR
SELECT * FROM customers
WHERE AGE > 27 ;

-- YASI 27'DEN BUYUK OLANLAR VE ULKESI ALMANYA 'DE' OLANLARI GETIR
SELECT * FROM customers
WHERE AGE > 27  AND   COUNTRY = 'DE' ;

-- TABLOYA YENI 2 TANE KOLON EKLENDI
ALTER TABLE `my_company_db`.`customers`
    ADD COLUMN `EMAIL` VARCHAR(100) NULL AFTER `COUNTRY`,
    ADD COLUMN `GENDER` VARCHAR(1) NULL AFTER `EMAIL`;



-- ID ICIN OTOMATIK SAYACI KULLANIYORUZ
ALTER TABLE `my_company_db`.`customers`
    CHANGE COLUMN `CUSTOMER_ID` `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT ;


-- YENI BIR KAYIT EKLENECEK
insert into customers (FIRST_NAME, LAST_NAME, AGE, COUNTRY, EMAIL, GENDER)
values ('Ali', 'Garip', 26, 'USA', 'mpinck0@typepad.com', 'M');

-- BUTUN KAYITLI MUSTERILERI LISTELE
SELECT * FROM customers;




-- ULKESI ALMANYA OLAN MUSTERILERIMIZI LISTELE
SELECT * FROM customers
WHERE COUNTRY = 'DE';



-- ULKESI ALMANYA OLAN VE KADIN MUSTERILERIMIZI LISTELE
SELECT * FROM customers
WHERE COUNTRY = 'DE' AND GENDER = 'F';

-- SADECE ADI, SOYADI VE ULKE KODU OLSUN. ULKESI ALMANYA OLAN ERKEK MUSTERILERIMIZI LISTELE
SELECT COUNTRY, FIRST_NAME, LAST_NAME FROM customers
WHERE COUNTRY = 'DE' AND GENDER = 'M';


-- ULKESI ALMANYA VEYA TURKIYE OLAN MUSTERILERIMI GETIR
SELECT  * FROM customers
WHERE COUNTRY = 'DE' OR COUNTRY ='TR';


-- ULKESI ALMANYA VEYA TURKIYE OLAN    VE   25 YAŞINDAN BUYUK MUSTERILERIMI GETIR
SELECT  * FROM customers
WHERE (COUNTRY = 'DE' OR COUNTRY ='TR')   AND  AGE > 25;

-- ULKESI ALMANYA OLMAYANLAR
SELECT  * FROM customers
WHERE COUNTRY != 'DE';

-- ULKESI ALMANYA OLMAYANLAR
SELECT  * FROM customers  WHERE  NOT COUNTRY  = 'DE';


-- BUTUN ULKELER TEKIL
SELECT DISTINCT COUNTRY FROM customers;


-- KAC MUSTERI VAR? SAYISINI VER.
SELECT count(*) FROM customers;

-- KAC MUSTERININ EMAILI VAR? SAYISINI VER.
SELECT count(EMAIL) FROM customers;


-- MUSTERILERIMIZIN YASLARI TOPLAMI KAC?
SELECT sum(AGE) FROM customers;

-- MUSTERI KITLEMIN YAS ORTALAMASI
SELECT AVG(AGE) FROM customers;


-- EN KUCUK MUSTERIMIN YASI KACTIR?
SELECT MIN(AGE) FROM customers;



-- EN BUYUK MUSTERIMIN YASI KACTIR?
SELECT max(AGE) FROM customers;

-- LAKAP ALIAS KULLANIMI
SELECT max(AGE) AS EnBuyuk
FROM customers;

-- LAKAP ALIAS KULLANIMI BIRDEN FAZLA KELIMEDEN OLUSURSA TIRNAK ICINE ALINIR
SELECT max(AGE) AS "En Buyuk"
FROM customers;


-- LAKAP ALIAS KULLANIMINDAKI AS KELIMESINI YAZMAK ZORUNLU DEGILDIR
SELECT max(AGE) EnBuyuk
FROM customers;

-- LAKAP ALIAS KULLANIMINDAKI AS KELIMESINI YAZMAK ZORUNLU DEGILDIR
SELECT max(AGE) "En Buyuk"
FROM customers;

-- ULKELERI TEKIL OLARAK LISTELE
SELECT  DISTINCT COUNTRY FROM customers;

-- KAC ULKE VAR?
 SELECT  COUNT(COUNTRY) FROM customers;



-- HANGI ULKEDEN TOPLAM KAC TANE VAR?
SELECT  COUNT(DISTINCT COUNTRY) FROM customers;


-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD)
SELECT FIRST_NAME AS CUS_FIRST,  LAST_NAME AS CUS_LAST  FROM customers;

-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD)
SELECT  CUSTOMER_ID AS CUS_ID,    FIRST_NAME AS CUS_FIRST,    LAST_NAME AS CUS_LAST    FROM customers;


-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD) SADE YAZIMI
SELECT  CUSTOMER_ID C_ID,    FIRST_NAME  C_FIRST,    LAST_NAME C_LAST    FROM customers;


-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD) TABLO ICIN
SELECT  customers.CUSTOMER_ID,    customers.FIRST_NAME,   customers.LAST_NAME     FROM customers;

-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD) TABLO ICIN AS kullanıldı
SELECT  c.CUSTOMER_ID,    c.FIRST_NAME,   c.LAST_NAME     FROM customers AS c;

-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD) TABLO ICIN AS YOK
SELECT  c.CUSTOMER_ID,    c.FIRST_NAME,   c.LAST_NAME     FROM customers c;


-- ALIAS (LAKAP, TAKMA ISIM, TAKMA AD) HEM KOLONLAR ICIN HEM DE TABLO ICIN
SELECT  c.CUSTOMER_ID ID ,
        c.FIRST_NAME FIRST,
        c.LAST_NAME  LAST
FROM customers c;


-- AD VE SOYAD BIRLESIK YAZDIRILACAK - CONCAT KOLONLARI BIRLESTIRIR
SELECT CONCAT(FIRST_NAME, ' ',  LAST_NAME) FULLNAME FROM customers;


-- YENI BIR KAYIT EKLE
insert into my_company_db.customers
    (FIRST_NAME, LAST_NAME, AGE, COUNTRY, EMAIL, GENDER)
values
    ('Robenia', 'Riden', 8, 'ID', 'rriden0@npr.org', 'F');
    
SELECT COUNT(*) FROM customers;



-- TOPLU HALDE VERI GIRISI 
insert into my_company_db.customers (FIRST_NAME, LAST_NAME, AGE, COUNTRY, EMAIL, GENDER) 
values ('Turner', 'Tookey', 82, 'FI', 'ttookey1@cloudflare.com', 'M'),
 ('Baldwin', 'Lucken', 37, 'CY', 'blucken2@goo.ne.jp', 'M'),
 ('Opalina', 'Pilbeam', 100, 'VN', 'opilbeam3@hatena.ne.jp', 'F');

-- MUSTERI SAYISI KAC?
SELECT COUNT(*) FROM my_company_db.customers;





-- ID NUMARASI VERILEN BIR KAYDI SIL
DELETE FROM `my_company_db`.`customers` WHERE (`CUSTOMER_ID` = '2');

SELECT * FROM  my_company_db.customers;

-- BUTUN KAYITLARI SILER!!! MUTLAKA WHERE SART KISMI KULLANDIGIN EMIN OL!!! DIKKAT!!!
-- DELETE FROM my_company_db.customers;

-- SILINMIS BIRSEYI SILMEYE CALISIRSAN BU CALISIR AMA BIRSEY YAPMAZ.
DELETE FROM `my_company_db`.`customers` 
WHERE `CUSTOMER_ID` = '2';

-- VARSAYILAN SIRALAMA 0 - 9     A'DAN Z'YE DIR. VE VE VE ID PK.YE YAPILIR.
SELECT * FROM  my_company_db.customers;




-- ADA GORE SIRALAMA YAP. VARSAYILAN ASC    0'DAN - 9'A     A'DAN Z'YE
SELECT *
FROM  my_company_db.customers
ORDER BY FIRST_NAME ;


-- ADA GORE SIRALAMA YAP. VARSAYILAN ASC    0'DAN - 9'A     A'DAN Z'YE
SELECT *
FROM  my_company_db.customers
ORDER BY FIRST_NAME ASC ;



-- ADA GORE SIRALAMA YAP. VARSAYILAN DESC    9'DAN 0'A     Z'DEN A'YA
SELECT *
FROM  customers
ORDER BY FIRST_NAME DESC ;


-- MUSTERI EN KUCUKTEN EN BUYUGE DOGRU SIRALA
SELECT *
FROM customers
ORDER BY AGE;


-- MUSTERI EN BUYUKTEN EN KUCUGE DOGRU SIRALA
SELECT *
FROM customers
ORDER BY AGE DESC;


-- ULKELERI TERSTEN Z'DEN A'YA DOĞRU SIRALA    VE   YASA GORE SIRALA
SELECT *
FROM customers
ORDER BY COUNTRY DESC, AGE DESC;



-- ULKELERIN ISIMLERINI AL VE  KISI SAYISINA GORE SIRALA
SELECT COUNTRY, COUNT(*) AS KISI
FROM customers
GROUP BY COUNTRY
ORDER BY KISI DESC;

-- ULKELERIN ISIMLERINI AL.
-- KISI SAYISINA GORE SIRALA
-- YASI 52'DEN BUYUK MUSTERILERI AL
-- RUSYADAKI MUSTERILERIDEN BUNA UYAN KAC KISI VAR?
SELECT COUNTRY, COUNT(COUNTRY) AS TOTAL
FROM customers
WHERE AGE > 52
GROUP BY COUNTRY
HAVING COUNTRY = 'RU';

-- ULKELERIN ISIMLERINI AL
-- KISI SAYISINA GORE TERSTEN SIRALA
-- YASI 15'DEN BUYUK MUSTERILERI AL
-- ALMANYADA OLMAYAN MUSTERILERIN SAYISI
SELECT COUNTRY, COUNT(*) TOTAL_PERSON
FROM customers
WHERE AGE > 15
GROUP BY COUNTRY
HAVING NOT COUNTRY  = 'DE'
ORDER BY TOTAL_PERSON DESC ;


-- ULKELERIN ISIMLERINI AL
-- KISI SAYISINA GORE TERSTEN SIRALA
-- YASI 15'DEN BUYUK MUSTERILERI AL
-- ALMANYADA OLMAYAN MUSTERILERIN SAYISI
SELECT COUNTRY, COUNT(*) TOTAL_PERSON
FROM customers
WHERE AGE > 15
GROUP BY COUNTRY
HAVING     COUNTRY != 'DE'
ORDER BY TOTAL_PERSON DESC ;



--  TRUNCATE SAYAC DAHIL. TABLO ILK HALINE DONER.
-- TRUNCATE `my_company_db`.`customers`;

-- TABLOYU ORTADAN KALDIRIR YOK EDER.
-- DROP TABLE `my_company_db`.`customers`;

-- GUNCELLEMEDE VE SILMEDE SART KISMI COK ONEMLIDIR!!!
-- update yaparken PK dışında where condition yazılamıyor.
-- SET SQL_SAFE_UPDATES = 0; ayarını yapmak gerekiyor

UPDATE `my_company_db`.`customers`
SET
    `FIRST_NAME` = 'Barış',
    `LAST_NAME` = 'Cengiz'
WHERE (`CUSTOMER_ID` > 10  );

SELECT * FROM customers;

