CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1 NOT NULL
    , FIRST_NAME VARCHAR2(70)
    , LAST_NAME VARCHAR2(75)
    , AGE INT
    , COUNTRY VARCHAR2(65)
    , CONSTRAINT CUSTOMERS_PK PRIMARY KEY
    (
     CUSTOMER_ID
        )
    ENABLE
);


INSERT INTO "MY_COMPANY_DB"."CUSTOMERS" (FIRST_NAME, LAST_NAME, AGE, COUNTRY) VALUES ('Ahmet', 'Koray', '25', 'DE');
INSERT INTO "MY_COMPANY_DB"."CUSTOMERS" (FIRST_NAME, LAST_NAME, AGE, COUNTRY) VALUES ('Ali', 'Güzel', '22', 'FR');
INSERT INTO "MY_COMPANY_DB"."CUSTOMERS" (FIRST_NAME, LAST_NAME, AGE, COUNTRY) VALUES ('Cihan', 'Çelik', '28', 'TR');


SELECT * FROM CUSTOMERS;

-- ŞART yaşı 22'den büuük kayıtlar
SELECT * FROM CUSTOMERS
WHERE AGE > 22;